### ISSUE TITLE
Aliasing effect with TiledMapAppState

### ISSUE THREAD

**Issue by DanaOtken** [jmecn/TMXLoader#5]
I'm not sure this so much needs changing the code as noting in comments the potential issue and fix, because most people using this library will probably use TiledMapAppState as a code example or superclass rather than as-is, but my first test after compiling the library (trying to display Tiled's "desert.tmx" example map, whose tile image has noticeable black gutters) ended up requiring quantizing the map's local translation to fix "tearing" due to momentary rounding issues with tile boundaries, similar to what happens if you turn on JME's anti-aliasing.

What I ended up changing to make the map smoothly pan (this certainly isn't elegant, or something I think should go into the main code, but it explains what I'm referring to):
```
public void move(float value, boolean sideways) {
               ...
                positionVisual(mapTranslation);// replacing map.getVisual().setLocalTranslation(mapTranslation);
	}

	private void drag(boolean isPressed) {
               ...
                        positionVisual(mapTranslation);// replacing map.getVisual().setLocalTranslation(mapTranslation);
		}
	}

        Vector3f pv_work=new Vector3f();
        protected void positionVisual(Vector3f pos) {
            pv_work.setX((float)Math.floor(pos.getX()));
            pv_work.setY((float)Math.floor(pos.getY()));
            pv_work.setZ((float)Math.floor(pos.getZ()));
            map.getVisual().setLocalTranslation(pv_work);
        }

```
Since the class already keeps its own copy of the "real" translation, I just needed to consistently convert that into a sanitized version for the rendering engine's benefit.

Again, this isn't so much something I think needs to get fixed as a tweak other people are likely to need to know is an option.

**Comment by jmecn** [comment]
Thanks for your advice, suggest accepted.
